global:
  marketplace-ami: false
  owner: jorge@aviatrix.com
  qsname: aviatrix-nggthmp
  regions:
    - us-east-1
  reporting: true
tests:
  aviatrix-nggthmp:
    parameter_input: aviatrix-nggthmp-params.json
    template_file: aviatrix-nggthmp.template
  # quickstart-aviatrix-master:
  #   parameter_input: quickstart-aviatrix-master-params.json
  #   template_file: quickstart-aviatrix-master.template
